required-players: 2
countdown-seconds: 30
lobby-spawn:
  world: world
  x: 129.7
  y: 99
  z: 53.4
  yaw: 178.6
  pitch: 1.5

arenas:
  0:
    world: 'world'
    x: 112.6
    y: 99
    z: 56.4
    yaw: 177
    pitch: 9.3
  1:
    world: 'world'
    x: 100.3
    y: 99
    z: 56.9
    yaw: 177.6
    pitch: 4.9